feature/header-my-library
kostusta/filmoteka-team-project-js pull request #2
Opened 2022-01-29 09:54 UTC by andriydzyunyak

add markup and styles for header my-library

2022-01-29 16:35 UTC, kostusta requested changes

2022-01-29 16:35 UTC, kostusta commented on src/partials/my-library-header.html
> +      <a class="header__home-link link" href="./" lang="en" target="_self">
Добавляй ссылку на index.html

2022-01-29 16:35 UTC, kostusta commented on src/partials/my-library-header.html
> +          <a class="site-nav__link link" href="./" target="_self">HOME</a>
Добавляй ссылку на index.html

2022-01-29 16:35 UTC, kostusta commented on src/partials/my-library-header.html
> +          <a class="site-nav__link site-nav__link--current link" href="./" target="_self"
Добавляй ссылку на my-library.html

2022-01-29 16:35 UTC, kostusta commented on src/sass/_my-library-header.scss
> +        font-family: $font-raleway;
Скорее всего это твоя локальная переменная. Пропиши руками font-family или создай в начале файла се необходимые переменные

2022-01-29 16:35 UTC, kostusta commented on src/sass/_my-library-header.scss
> +     @extend %link;
Не понятно от чего наследуются стили. В общих базовых стилях нет класса link

2022-01-29 16:35 UTC, kostusta commented on src/sass/_my-library-header.scss
> +        @extend %link;
Не понятно от чего наследуются стили. В общих базовых стилях нет класса link

2022-01-29 18:01 UTC, kostusta requested changes

2022-01-29 18:01 UTC, kostusta commented on src/partials/my-library-header.html
> +<header class="header">
Можно убрать этот тег, я добавлял его в основной html файл. Внутри этого тега подключен твой partial

2022-01-29 22:56 UTC, andriydzyunyak commented on src/partials/my-library-header.html
> +      <a class="header__home-link link" href="./" lang="en" target="_self">
добавил

2022-01-29 22:56 UTC, andriydzyunyak commented on src/partials/my-library-header.html
> +          <a class="site-nav__link link" href="./" target="_self">HOME</a>
добавил

2022-01-29 22:56 UTC, andriydzyunyak commented on src/partials/my-library-header.html
> +          <a class="site-nav__link site-nav__link--current link" href="./" target="_self"
добавил

2022-01-29 22:57 UTC, andriydzyunyak commented on src/sass/_my-library-header.scss
> +        font-family: $font-raleway;
исправил

2022-01-29 22:57 UTC, andriydzyunyak commented on src/sass/_my-library-header.scss
> +     @extend %link;
исправил

2022-01-29 22:57 UTC, andriydzyunyak commented on src/sass/_my-library-header.scss
> +        @extend %link;
исправил

2022-01-29 23:02 UTC, andriydzyunyak commented on src/partials/my-library-header.html
> +<header class="header">
исправил

2022-01-30 09:53 UTC, kostusta requested changes

2022-01-30 09:53 UTC, kostusta commented on src/sass/main.css
> +ul {
Необходимо перед пушем и пулл риквестом удалить этот файл из папки src/sass

2022-01-30 09:53 UTC, kostusta commented on src/sass/main.css.map
> +{
Необходимо перед пушем и пулл риквестом удалить этот файл из папки src/sass

2022-01-30 20:27 UTC, kostusta approved these changes

2022-01-30 20:27 UTC, merged