My library
kostusta/filmoteka-team-project-js pull request #4
Opened 2022-01-29 17:48 UTC by alexlex7

Added styles for galery

2022-01-29 18:30 UTC, kostusta requested changes

2022-01-29 18:30 UTC, kostusta commented on src/partials/galery.html
> +        <div><img src="images/Rectangle_mobile.jpg" alt="" /></div>
Мне кажется, что каждую карточку лучше обернуть в ссылку с помощью тега <!-- <a></a> --!> поскольку при нажатии на карточку будет открываться модалка с детальным описание фильм. И еще нужно выкачать картинку для разного размера девайса и для ретины + обычного экрана чтоб в зависимости от размера устройства и разрешения экрана подгружалась правильная картинка.

Я бы сделала разметку одной карточки так:
<!--      <a class="" href="">
        <article class="card">
          <div class="обертка для картинки">
            <picture>
              <source srcset="./путь к картинке/имя картинки для десктопа@1x.jpg 1x, ./путь к картинке/имя картинки для десктопа@2x.jpg 2x" media="(min-width:1200px)"/>
              <source srcset="./путь к картинке/имя картинки для планшета@1x.jpg 1x, ./путь к картинке/имя картинки для планшета@2x.jpg 2x" media="(min-width:768px)"/>
              <source srcset="./путь к картинке/имя картинки для телефона@1x.jpg 1x, ./путь к картинке/имя картинки для телефона@2x.jpg 2x" media="(min-width:320px)"/>
              <img class="card__preview" src="./путь к картинке/имя картинки для десктопа@1x.jpg" alt=""/>
            </picture>
          </div>
          <div class="информация о фильме">
            <p class=""> Название фильна</p>
            <p class=""> Жанры фильма <span>Рейтинг фильма</span></p>
          </div>
        </article>
      </a> --!>

2022-01-29 18:30 UTC, kostusta commented on src/sass/_galery.scss
> +      padding: 60px 70px 0 70px;
По макету левый padding равен 71px. При таком значении для padding сумма обеих паддингов, ширины каждой карточки и мрджинов между карточками точно равна 1024px. Необходимо внести корректировку.

2022-01-30 07:32 UTC, alexlex7 commented on src/sass/_galery.scss
> +      padding: 60px 70px 0 70px;
Исправил.

2022-01-30 07:35 UTC, alexlex7 commented on src/partials/galery.html
> +        <div><img src="images/Rectangle_mobile.jpg" alt="" /></div>
Обернул карточку в ссылку, srcset не добавил так как у нас не будет изображений с разным разрешением.

2022-01-30 07:37 UTC, closed without merging